### ISSUE TITLE
let i be -3

### ISSUE THREAD

**Issue by marcfedorow** [EdikGres/exam_vector_t#6]
https://github.com/EdikGres/exam_vector_t/blob/be7ff0865ffae18c863c6dd0b2722da017f93193/exam_vector_t/VectorLib.cpp#L71

```cpp
vect->data[-3] = vect->data[-2]; 
```
does not seem nice

**Comment by EdikGres** [comment]
Thanks for the comment, the repository is old, there is no desire to update. Sorry.
